FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

LABEL maintainer="fmoralvi" \
      description="Tour of Heroes API" \
      version="1.0.0" \
      license="MIT"

WORKDIR /app

EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

RUN dotnet publish "tour-of-heroes-api.csproj" -c Release -o /app/publish

FROM base AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "tour-of-heroes-api.dll"]

